---
params:
    # either rse, pm, dba, dm
    position: pm
    position_title: "project manager"
output: md_document
---

```{r generate-job-ads, eval=FALSE, include=FALSE}
library(tidyverse)
library(fs)
position <- c(
    rse = "research software engineer",
    # Or team lead or other name?
    pm = "project manager",
    dba = "database administrator"
)
walk2(
    names(position),
    position,
    ~ rmarkdown::render(
        input = here::here("hiring/dif-project/_shared.Rmd"),
        output_file = here::here("hiring/dif-project/", 
                                 path_ext_set(str_replace_all(.y, " ", "-"), ".md")),
        params = list(position = .x, position_title = .y)
    ) 
)
```

# Job description for `r position`

<!--
Some resources for writing job descriptions:

- http://www.fortefoundation.org/site/DocServer/gendered_wording_JPSP.pdf?docID=16121
- https://www.linkedin.com/business/talent/blog/talent-acquisition/must-dos-for-writing-inclusive-job-descriptions
- https://harver.com/blog/inclusive-job-descriptions/
-->

The Steno Diabetes Center Aarhus (SDCA; https://www.stenoaarhus.dk/) is hiring
a team to work on a recently funded software and data project. This project
aims to build an open and scalable infrastructure Framework for working with,
discovering, and managing data that follows FAIR and open science principles.
A full description of the Framework project can be found at 
https://steno-aarhus.github.io/dif-project/.

SDCA is a center that brings together researchers and clinicians in an aim to
better integrate work on multiple aspects of diabetes treatment, research, and
education. The Framework project will be largely contributing to the research of
the center (https://www.stenoaarhus.dk/research/) as well as that of other
research centers and initiatives throughout Denmark.

Since SDCA was started only a few years ago, its technical and social
infrastructure are still being actively developed. As a result, all SDCA
personnel, including this current job along with the Framework team, have a
direct and impactful influence on how the culture and infrastructure is built
and developed. Aside from working on the Framework, other responsibilities for
this current job position, as well as the rest of the team, include contributing
to this (explicit and inclusive) culture, for instance by adding to our Common
Docs (https://steno-aarhus.github.io/research/).

## Responsibilities and tasks

The **primary** responsibility for all members of the Framework team will be
building and developing the newly started Framework project. More specifically,
tasks you will do include:

- Refining, critiquing, and improving on the schematic and details of the
Framework's final implementation and structure.
- Finding and reviewing similar projects to identify what to use and what can be
improved upon.
- Building, internal testing, and developing each component of the Framework into
Minimally Valuable Products for early external testing and refining.
- Writing public-facing, *beginner-friendly*, and accessible documentation on
contributing to and using the Framework.
- Creating and maintaining websites connected to the Framework (e.g. through
GitHub Pages).

All team members' **secondary responsibilities**:

- Contributing to tasks and projects related to the general administration or
building up of SDCA (e.g. writing and/or updating onboarding documentation).
- Assisting with building up general capacity and skills in
reproducibility/transparency of research data analyses throughout SDCA.
- Creating and running training sessions related to the Framework and to general
computational skills.

Responsibilities **specific to this position** also include:

```{asis, echo=params$position == "rse"}
- Building and interacting with RESTful APIs (or APIs in general)
- Reviewing contributed code and text.
* Assisting with or developing tools for improving analysis and workflow pipelines (e.g. making R packages and scripts)
```

```{asis, echo=params$position == "pm"}
- Planning, coordinating, and if necessary revising the tasks required to
complete the Framework.
- Tracking milestones and managing issues that arise such that work on the
Framework continues as smoothly as possible.
- Reviewing contributed code and text, accepting changes made.
- Facilitating, communicating, and coordinating with the team members on completing
the project tasks.
```

```{asis, echo=params$position == "dba"}
- Database management/administration
* Manage server and data
* Providing continued support for running projects with Statistics Denmark
```

```{asis, echo=params$position == "dm"}
- Database management/administration
* Manage server and data
- Work with DD2 project
- Experience in the Danish research computing environments, e.g., "forskermaskine" (research engine on Denmark Statistics (DST))
```

## Qualifications and experiences

All team members' should have at a minimum these **required** qualifications 
and experiences:

- Has worked on, started, or contributed to open source projects on open sharing
and collaborative platforms (e.g. Open Science Framework, GitHub, GitLab).
- Has used Git or other version control software on a fairly regular basis for
projects.
- Is proficient in communicating (written and oral) in English.

Other **optional, bonus** qualifications and experiences include that you have:

- Knowledge of and familiarity with general software development practices.
- Interest in or motivation to be involved in aspects of building up and
developing the culture and infrastructure of a newer organization.

Qualifications and experience **specific to this position** also include:

```{asis, echo=params$position == "rse"}
- Can develop software packages in either R or Python that abides by accepted
standard practices (e.g. CRAN or rOpenSci guidelines for R packages).
- Experienced or familiar with using R and/or Python for general programming tasks.

**Optional** (also can learn while on the job):

- Experience in or familiar with using HTML, CSS, and other web technologies.
- Familiar with general User Interface (UI) and/or User Experience (UX) design principles.
- Experience in or familiar with interacting with and/or developing APIs.

- (There is some overlap between software and data engineering, so some familiarity with
both is necessary)
```

```{asis, echo=params$position == "pm"}
```

```{asis, echo=params$position == "dba"}
* Data management experience
- Using Git and GitHub/GitLab
- Database management/administration
- Familiar with creating training material and teaching
- Experience in working on open source projects and with FAIR principles

- **CSV, SQL, and JSON format for data storage:** Are open source and established formats for data and other web information.
    - JSON (JavaScript Object Notation) is the Internet’s de facto standard format for information transfer.
    - CSV is well known to researchers.
    - SQL (a querying language and data storage format) is a widely used format for storing data.
```

```{asis, echo=params$position == "dm"}
* Write up documentation and provide support for working with Statistics Denmark projects
```

## Other job expectations and details

- The position can (depending on where applicant lives) largely be remote / work from home.
    - If you live or move to Aarhus for the position, we'd prefer that you come
    into the office once or twice a week.
    - If you live outside of Denmark, we expect (and will cover) for you to
    participate in occasional in person meetings (e.g. our annual research day).
- We don't expect you to have all the skills for the position and part of the
job is learning these skills. In process of learning them, we encourage you to
create training docs as you learn so knowledge and skills can be shared.
- **Benefits**:
    - Childcare, parental leave
    - Very flexible working hours
    - Others?
- **Contact details** if you have any specific questions about the position: (who? all of us?)
- Other details:
    - Supplement for buying necessary computing equipment?
    - Covering for in person interviews?
