---
format: 
  docx:
    reference-doc: instructions/rmd-reference.docx
editor:
  markdown:
    wrap: 72
    canonical: true
---

# Research software engineer for a research-data infrastructure framework

The [Department of Clinical Medicine](https://clin.au.dk/) at [Faculty
of Health](https://health.au.dk/en/) at Aarhus University, in
collaboration with the [Steno Diabetes Center
Aarhus](https://www.stenoaarhus.dk/) (SDCA), invites applications for
one "research software engineer" position to work (in person or remote)
with a team on a software and data engineering project, starting
September 1 or as soon as possible thereafter. The position is full-time
for up to 2 years.

As an employee at the Department of Clinical Medicine, you will be part
of what is probably the largest health science research department in
Denmark. Our clinical research covers all the medical specialities and
takes place in close collaboration with the university hospital and the
regional hospitals in the Central Denmark Region. We have approx. 30,000
square metres of modern research facilities for experimental surgery and
medicine, animal facilities and also advanced scanners at our disposal.
The department has overall responsibility for the Master's degree
programs in medicine and in molecular medicine. At the department we are
approx. 670 academic employees, 500 PhD students and 160
technical/administrative employees who are cooperating across
disciplines. As an employee, you will be working on Aarhus University
Hospital or another hospital in the Central Denmark Region. You can read
more about the department [here](https://clin.au.dk/) and about the
faculty [here](https://health.au.dk/en/).

SDCA is a center that brings together researchers and clinicians in an
aim to better integrate work on multiple aspects of diabetes treatment,
research, and education.

This project aims to build an open and scalable data infrastructure
framework for working with, discovering, and managing data that follows
FAIR and open science principles. This is a *software* project that
focuses on working with data, but not on data itself. A description of
the project (called Seedcase) can be found at
<https://steno-aarhus.github.io/seedcase-project/>. The Seedcase project
will be contributing to the research of SDCA
(<https://www.stenoaarhus.dk/research/>) as well as that of other Steno
centers and research initiatives throughout Denmark.

SDCA is still a young and growing center, so its technical and social
infrastructure are still being actively developed and refined. All SDCA
personnel, including this current position and the rest of the Seedcase
team, have a direct and impactful influence on the building and
developing of the culture and infrastructure. Aside from working on
Seedcase, other responsibilities for the research software engineer, as
well as the rest of the team, include contributing to building this
organization and culture.

## Your job responsibilities

As the research software engineer, you will be:

-   Building and developing RESTful APIs (or APIs in general) for
    Seedcase

-   Building and developing the front end of the application

-   Writing and reviewing code and documentation

-   Assisting with or developing tools for improving analysis and
    workflow pipelines related to using Seedcase (e.g. making Python/R
    packages and scripts)

While there are many tasks to work on for the Seedcase project, the
position offers a large amount of autonomy and freedom. As long as tasks
are completed and we make progress on our milestones, there is the
potential for the applicant to collaborate on other research projects
within AU and SDCA. If the applicant has interest and motivation in
those other projects or wishes to learn new skills and knowledge, we
definitely encourage and support pursuing these types of activities.

### Team-wide responsibilities

The **primary** responsibility for all members of the Seedcase team will
be building and developing the Seedcase project. More specifically,
tasks will include:

-   Refining, critiquing, and improving on the descriptions of the
    use-cases and the design and architecture of Seedcase

-   Finding and reviewing similar projects to identify what to use and
    what can be improved upon

-   Building, internally testing, and developing each component of
    Seedcase into Minimally Valuable Products for early external testing
    and refining

-   Writing public-facing, *beginner-friendly*, and accessible
    documentation on contributing to and using Seedcase

-   Creating and maintaining websites connected to Seedcase (e.g.
    through GitHub Pages)

All team members' *secondary* responsibilities (dependent on time
available outside of the Seedcase project):

-   Contributing to tasks and projects related to the general
    administration or building up of the general research environment
    (e.g. writing and/or updating onboarding documentation)

-   Assisting with building up general capacity and skills in
    computational and programmatic skills and knowledge through training
    and documentation

-   Creating teaching material and running training sessions related to
    Seedcase

-   Contributing to Steno-wide data and software engineering activities,
    such as building tools to help streamline or automating common tasks
    that staff and researchers do

*Note*, while the team as a whole will need to complete these tasks, any
individual member of the team *does not* need to do all these tasks and
instead will be assigned specific sections of the project.

You will report to the Unit Head Annelli Sandbæk and to the team leader
Luke Johnston.

## Your competencies

We expect, at a minimum, that you:

-   Are proficient in communicating (written and oral) in English

-   Are motivated, interested, and comfortable with working on projects
    that have recently started and that require contributing to a
    diverse set of tasks typical of the early stages of any project

-   Have demonstrated knowledge of and experience in using either
    Python, JavaScript, or R for general programming tasks (need to be
    open to learning them)

-   Have used Git or other version control software on a fairly regular
    basis for projects

-   Have knowledge or experience in developing user-facing content, such
    as websites, through HTML and CSS.

And we prefer, but don't require, that you:

-   Have developed or contributed to software packages in Python or R
    that abides by community-accepted standard practices (e.g. PIP or
    CRAN)

-   Have worked on, started, or contributed to open source projects on
    open sharing and collaborative platforms (e.g. GitHub, GitLab)

-   Have knowledge of and familiarity with *general* software
    development practices

-   Are interested in or motivated to be involved in aspects of building
    up and developing the culture and infrastructure of a newer
    organization

-   Have knowledge of and experience in implementing and adhering to
    FAIR/open principles

-   Are familiar with general User Interface (UI) and/or User Experience
    (UX) design principles

-   Have experience in or familiarity with interacting with and/or
    developing APIs

-   Are familiar with general data engineering practices

-   Have some experience or familiarity with the research environment
    and its specific set of needs

## Who we are/will be

We currently have a core team of one full-time research software
engineers, a data manager, a database administrator, a team leader, as
well as affiliate researchers and the primary investigator. We have a
great working environment with an informal and positive atmosphere.

## What we offer

-   The position can (depending on where the applicant lives) be largely
    remote / work from home.

    -   If you live or move to Aarhus for the position, we expect that
        you come into the office at SDCA at least twice a week. SDCA
        office is placed at Steno Diabetes Center Aarhus, Palle
        Juul-Jensens Boulevard 99, Building A, 8200 Aarhus N, Denmark
    -   If you live outside of Denmark, we expect (and will cover) for
        you to participate in bigger in person meetings/events

-   The working hours are flexible.

-   Any necessary hardware or software will be provided or covered for.

-   The position allows for a lot of freedom and autonomy in work and in
    the decision making on the direction the project will take.

## Contact information

-   If you have any specific questions about the position, **contact**
    Luke Johnston
    ([lwjohnst\@clin.au.dk](mailto:lwjohnst@clin.au.dk){.email}).

## Terms of employment

Terms of employment and pay are regulated by the collective agreement
between the Ministry of Finance and the applicable collective agreement.

## Application

Your application must include the following:

-   Motivated application
-   Curriculum Vitae
-   Indication of education (a copy of the diplomas should be uploaded)
-   References/recommendations can be uploaded separately in the
    recruitment system

The **deadline for applications** is June 9th, 2023. We expect to
conduct job interviews sometime during the weeks of 24-26 (June 12-30).

We refer to the faculty's [Guideline for
applicants](https://health.au.dk/fileadmin/www.health.au.dk/Om_Health_Ekstern/Ledige_stillinger/Ansaettelsesprocedurer/PDF/Guidelines-for-applicants-to-technical-administrative-positions.pdf).

Aarhus University's ambition is to be an attractive and inspiring
workplace for all and to foster a culture in which each individual has
opportunities to thrive, achieve and develop. We view equality and
diversity as assets, and we welcome all applicants.

*The application must be submitted via Aarhus University's recruitment
system, which can be accessed under the job advertisement on Aarhus
University's website.*

**Aarhus University**

*Aarhus University is an academically diverse and research-intensive
university with a strong commitment to high-quality research and
education and the development of society nationally and globally. The
university offers an inspiring research and teaching environment to its
38,000 students (FTEs) and 8,000 employees, and has an annual revenues
of EUR 885 million. Learn more at
[international.au.dk](https://www.international.au.dk/).*
