---
title: "Design"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Design}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Principles

-   Wherever possible, output a tibble, otherwise a vector.

## Naming scheme

### Calendar (`cal`)

-   Objects:
    -   events: In calendar terms, an event is an activity with a start
        and end date and time in a calendar.
    -   ical: The iCal format is a standard for calendar data exchange.
-   Actions:
    -   read: Reading from a file or URL.
    -   create: Creating a new event.
    -   write: Writing to a file.

### GitHub (`gh`)

-   Objects: users, teams, issues, issue templates, projects, repos,
    labels
-   Actions: get, add, create, remove, as, verify

Functions to be developed based on naming scheme:

``` r
gh_create_team(name)
gh_remove_from_org(username)
gh_remove_from_team(username, team)
```

### Epi Group Meetings (`epi`)

-   Objects:
    -   sessions: Sessions are the regular (monthly) events of the
        group.
    -   calendar: This is the Epidemiology specific calendar.
    -   GitHub session issues: These are the issues created for each
        session.
-   Actions: get, create, update

Functions:

``` r
epi_create_dates()
epi_create_meeting_issues(dates)

epi_update_calendar(url, data)
```

### General

-   Objects: gh
-   Actions: verify
